version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            npm ci
            npm run test
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: 
          name: Add server to known hosts
          command: |
            ssh-keyscan $IP_ADDRESS >> ~/.ssh/known_hosts
      - run:
          name: Build and start the app
          command: |
            ssh "$USER"@"$IP_ADDRESS" << 'EOF'
            set -e
            cd alexa-fairy-tales
            git fetch origin
            git reset --hard origin/master
            nvm use 12
            npm ci
            npm run build
            PORT=3333 npm run deploy
            EOF
workflows:
  version: 2
  release:
    jobs:
      - test
      - deploy

