version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      # we are telling docker to get another container and link it
      # - setup_remote_docker:
      #     docker_layer_caching: false
      - run: ssh-keyscan $IP_ADDRESS >> ~/.ssh/known_hosts
      - run:
          name: Build and start the app
          command: |
            ssh "$USER"@"$IP_ADDRESS" << EOF
            cd alexa-fairy-tales
            git pull
            nvm use 12
            npm run build
            lsof -i :3333 | grep node | awk '{print $2}' | xargs -n 1 kill
            PORT=3333 nohup node ./lib/index.js > process.out 2> process.err < /dev/null &
            exit
            EOF
            # docker push here
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - deploy

