version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      # we are telling docker to get another container and link it
      # - setup_remote_docker:
      #     docker_layer_caching: false
      - run: ssh-keyscan $IP_ADDRESS >> ~/.ssh/known_hosts
      - run:
          name: Build and start the app
          command: |
            ssh "$USER"@"$IP_ADDRESS" << 'EOF'
            set -e
            cd alexa-fairy-tales
            git pull
            nvm use 12
            npm run build
            PROCESS_ID=$( lsof -i :3333 -t )
            echo "Killing $PROCESS_ID"
            kill $PROCESS_ID
            ERROR_FILE="./process.err"
            LOG_FILE="./process.out"
            rm "$ERROR_FILE"
            PORT=3333 nohup node ./lib/index.js > "$LOG_FILE" 2> "$ERROR_FILE" < /dev/null &
            sleep 15
            if [ -f "$ERROR_FILE" ]; then
              cat "$LOG_FILE"
              cat "$ERROR_FILE"
              exit 1
            else 
              echo "$FILE does not exist"
              cat "$LOG_FILE"
              exit
            fi
            EOF
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - deploy

