version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      # we are telling docker to get another container and link it
      # - setup_remote_docker:
      #     docker_layer_caching: false
      - run:
          name: Build and start the app
          command: |
            ssh "$USER"@"$IP_ADDRESS"
            cd alexa-fairy-tales
            git pull
            nvm use 12
            npm run build
            lsof -i :3333 | grep node | awk '{print $2}' | xargs kill
            PORT=3333 node ./lib/index.js &
            exit
            # docker push here
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - deploy

